all: ext2_cp ext2_mkdir

ext2_cp: ext2_cp.c ext2_helper.c
		gcc -Wall -g -o cp ext2_cp.c 

ext2_mkdir: ext2_mkdir.c ext2_helper.c
		gcc -Wall -g -o mkdir ext2_mkdir.c 

ext2_ln: ext2_ln.c ext2_helper.c
		gcc -Wall -g -o ln ext2_ln.c 